version: '2'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql
    environment: &mysqlenv
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_DATABASE: silverstripe_database
